// Required by Webpack - do not touch
require.context('../', true, /\.(html|json|txt|dat)$/i)
require.context('../images/', true, /\.(gif|jpg|png|svg|eot|ttf|woff|woff2)$/i)
require.context('../stylesheets/', true, /\.(css|scss)$/i)

// First: Set up your name
let std_name = "RJ Larsen"
document.querySelector('#std_name').innerHTML = `<strong>${std_name}</strong>`

//Then: comes everything else
import * as d3 from 'd3';

// Smiley Face
let svg1 = d3.select('main').append('svg')
    .attr('width', 110)
    .attr('height', 110)
    .style('background', '#eee')
    .style('fill', 'transparent')
let face = svg1.append('circle')
    .attr('cx', 55)
    .attr('cy', 55)
    .attr('r', 30)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let leftEye = svg1.append('circle')
    .attr('cx', 40)
    .attr('cy', 45)
    .attr('r', 3)
    .style('stroke', '#eee')
    .style('fill', '#eee')
let rightEye = svg1.append('circle')
    .attr('cx', 70)
    .attr('cy', 45)
    .attr('r', 3)
    .style('stroke', '#eee')
    .style('fill', '#eee')
let mouth = svg1.append('path')
    .style('stroke', '#eee')
    .style('fill', 'none')
    .style('stroke-width', 3)
    .attr('d', 'M35,65 Q55,80 75,65')

function animate_smiley(){
    face
        .transition()
        .duration(1300)
        .attr('r', 50)
    rightEye
        .transition()
        .duration(1300)
        .attr('cx', 75)
        .attr('cy', 40)
        .attr('r', 5)
    leftEye
        .transition()
        .duration(1300)
        .attr('cx', 35)
        .attr('cy', 40)
        .attr('r', 5)
    mouth
        .transition()
        .duration(1300)
        .attr('d', 'M25,65 Q55,85 85,65')
}
animate_smiley();

// Stereo
let svg2 = d3.select('main').append('svg')
    .attr('width', 110)
    .attr('height', 110)
    .style('background', '#eee')
    .style('fill', 'transparent')
let stereoBox = svg2.append('rect')
    .attr('x', 25)
    .attr('y', 5)
    .attr('width', 60)
    .attr('height', 100)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let speaker1 = svg2.append('circle')
    .attr('cx', 55)
    .attr('cy', 30)
    .attr('r', 8)
    .style('stroke', '#eee')
    .style('fill', '#eee')
let speaker2 = svg2.append('circle')
    .attr('cx', 55)
    .attr('cy', 70)
    .attr('r', 6)
    .style('stroke', '#eee')
let speaker3 = svg2.append('circle')
    .attr('cx', 55)
    .attr('cy', 70)
    .attr('r', 20)
    .style('stroke', '#eee')
    .style('stroke-width', 2)

function animate_stereo(){
    speaker2
        .transition()
        .attr('r', 5.5)
        .transition()
        .attr('r', 6)
        .transition()
        .attr('r', 5.5)
        .transition()
        .attr('r', 6)
    speaker3
        .transition()
        .attr('r', 22)
        .transition()
        .attr('r', 20)
        .transition()
        .attr('r', 22)
        .transition()
        .attr('r', 20)
}
animate_stereo()

// musical note
let svg3 = d3.select('main').append('svg')
    .attr('width', 110)
    .attr('height', 110)
    .style('background', '#eee')
    .style('fill', 'transparent')
let note1 = svg3.append('ellipse')
    .attr('cx', 23)
    .attr('cy', 84)
    .attr('rx', 10)
    .attr('ry', 11)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let note2 = svg3.append('ellipse')
    .attr('cx', 67)
    .attr('cy', 72)
    .attr('rx', 10)
    .attr('ry', 11)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let post1 = svg3.append('rect')
    .attr('x', 27.75)
    .attr('y', 36)
    .attr('width', 5)
    .attr('height', 50)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let post2 = svg3.append('rect')
    .attr('x', 71.7)
    .attr('y', 30)
    .attr('width', 5)
    .attr('height', 40)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let post3 = svg3.append('rect')
    .attr('x', 27.7)
    .attr('y', 18)
    .attr('width', 49)
    .attr('height', 18)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')

function animate_note(){
    note1
        .transition()
        .attr('cy', 80)
        .attr('cx', 23)
        .transition()
        .attr('cy', 84)
        .attr('cx', 23)
        .transition()
        .attr('cy', 80)
        .attr('cx', 23)
        .transition()
        .attr('cy', 84)
        .attr('cx', 23)
    note2
        .transition()
        .attr('cy', 68)
        .attr('cx', 67)
        .transition()
        .attr('cy', 72)
        .attr('cx', 67)
        .transition()
        .attr('cy', 68)
        .attr('cx', 67)
        .transition()
        .attr('cy', 72)
        .attr('cx', 67)
    post1
        .transition()
        .attr('y', 32)
        .transition()
        .attr('y', 36)
        .transition()
        .attr('y', 32)
        .transition()
        .attr('y', 36)
    post2
        .transition()
        .attr('y', 26)
        .transition()
        .attr('y', 30)
        .transition()
        .attr('y', 26)
        .transition()
        .attr('y', 30)
    post3
        .transition()
        .attr('y', 14)
        .transition()
        .attr('y', 18)
        .transition()
        .attr('y', 14)
        .transition()
        .attr('y', 18)

}
animate_note();

//dumbbell
let svg4 = d3.select('main').append('svg')
    .attr('width', 110)
    .attr('height', 110)
    .style('background', '#eee')
    .style('fill', 'transparent')
let bar = svg4.append('rect')
    .attr('x', -25)
    .attr('y', 70)
    .attr('height', 15)
    .attr('width', 50)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
    .attr('transform', 'rotate(-45)')
let topWeight = svg4.append('rect')
    .attr('x', 58)
    .attr('y', -43)
    .attr('height', 15)
    .attr('width', 40)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
    .attr('transform', 'rotate(45)')
let bottomWeight = svg4.append('rect')
    .attr('x', 58)
    .attr('y', 28)
    .attr('height', 15)
    .attr('width', 40)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
    .attr('transform', 'rotate(45)')
let barEndBottom = svg4.append('rect')
    .attr('x', -56)
    .attr('y', 70)
    .attr('height', 15)
    .attr('width', 10)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
    .attr('transform', 'rotate(-45)')
let barEndTop = svg4.append('rect')
    .attr('x', 46)
    .attr('y', 70)
    .attr('height', 15)
    .attr('width', 10)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
    .attr('transform', 'rotate(-45)')
function animate_dumbbell(){
    barEndTop
        .transition()
        .duration(1300)
        .attr('y', 58)
        .attr('height', 40)
    barEndBottom
        .transition()
        .duration(1300)
        .attr('y', 58)
        .attr('height', 40)
}
animate_dumbbell();

//basketball
let svg5 = d3.select('main').append('svg')
    .attr('width', 110)
    .attr('height', 110)
    .style('background', '#eee')
    .style('fill', 'transparent')
let ball = svg5.append('circle')
    .attr('cx', 55)
    .attr('cy', 55)
    .attr('r', 0)
    .style('stroke', '#334A9DFF')
    .style('fill', '#334A9DFF')
let vertLine = svg5.append('path')
    .attr("d", 'M55,4 L55,106')
    .style('stroke-width', 3)
    .style('stroke', '#eee')
let horLine = svg5.append('path')
    .attr("d", 'M4,55 L106,55')
    .style('stroke-width', 3)
    .style('stroke', '#eee')
let topLine = svg5.append('path')
    .style('stroke', '#eee')
    .style('fill', 'none')
    .style('stroke-width', 3)
    .attr('d', 'M20,15 Q55,65 90,15')
let bottomLine = svg5.append('path')
    .style('stroke', '#eee')
    .style('fill', 'none')
    .style('stroke-width', 3)
    .attr('d', 'M20,95 Q55,45 90,95')

function animate_basketball(){
    ball
        .transition()
        .duration(1300)
        .attr('r', 50)
    vertLine
        .transition()
        .duration(1300)
        .attr('transform', 'rotate(360)')
    horLine
        .transition()
        .duration(1300)
        .attr('transform', 'rotate(360)')
    topLine
        .transition()
        .duration(1300)
        .attr('transform', 'rotate(360)')
    bottomLine
        .transition()
        .duration(1300)
        .attr('transform', 'rotate(360)')
}
animate_basketball();

